# SyncPlay Server Configuration
server.port=8080

# TMDB API Access Token
tmdb.access-token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNmViOTIxZDczYTdmMDgyMDJjZjRiNjJkZWE4ZTcwMCIsIm5iZiI6MTc3NDM5OTY5NS42NzIsInN1YiI6IjY5YzMzMGNmOTYxZmZlOWFmZDZhYzA5YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.kSddRgvZuFP6as-RkpfFIFSo2P7P2UqyVuotXKAbKJA
tmdb.base-url=https://api.themoviedb.org/3

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3308/syncplay?serverTimezone=Asia/Seoul
spring.datasource.username=syncplay
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.syncplay.server=DEBUG